version: "3"

services:
  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - /mnt/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${ENV_MYSQL_USER_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - nextcloud_db
    volumes:
      - /mnt/nextcloud:/var/www/html
    restart: always

  dlna_server:
    image: vladgh/minidlna
    restart: always
    volumes:
      - /mnt/nextcloud/data/MYUSER/files/Shared/Musics:/media/audio
      - /mnt/nextcloud/data/MYUSER/files/Shared/Videos:/media/video
    environment:
      - MINIDLNA_MEDIA_DIR_1=A,/media/audio
      - MINIDLNA_MEDIA_DIR_2=V,/media/video
      - MINIDLNA_FRIENDLY_NAME=MY_MEDIA_SERVER
