version: "3"

services:
  nextcloud_db:
    image: mariadb:latest
    restart: always
    volumes:
      - /mnt/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${ENV_MYSQL_USER_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: nextcloud:latest
    ports:
      - 8080:80
    links:
      - nextcloud_db
    volumes:
      - /mnt/nextcloud:/var/www/html
    restart: always
